import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { mdbConnect } from "@/lib/mongo";
import { inspect } from "util";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const conn = await mdbConnect();
  // console.log("Return:", inspect(conn));
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
